### ISSUE TITLE
Não Funciona, Aparentemente

### ISSUE THREAD

**Issue by Design-ADCD** [luizwbr/Correios-VirtueMart-3#1]
Olá! Instalei o plugin, e a opção para criar uma nova forma de envio através dos correios aparece para mim. Porém ela aparece muito estranha e mesmo após de completar o cadastramento, ela não funciona no site. Não aparece qualquer forma de envio.

**Comment by erickncnunes** [comment]
Provavelmente algum problema na sua instalação do joomla, funcionando corretamente em vários sites. Qual versão do joomla e vm está utilizando ?

**Comment by Design-ADCD** [comment]
Olá Erick!
Já consegui resolver esse problema diretamente com o Luiz Weber!
O meu problema é que não estava configurado para Quilograma. Ele só funciona com Kg.
