### ISSUE TITLE
1 frete por produto

### ISSUE THREAD

**Issue by informatiza** [luizwbr/Correios-VirtueMart-3#11]
o plugin não está funcionando a opção de calculo de 1 frete por produto, se eu tenho 3 produtos  por exemplo no carrinho, ele só está calculando de 1 produto

**Comment by luizwbr** [comment]
Rafael, você está usando a última versão, certo?

Tenta fazer um teste com produtos com as mesmas dimensões para ver se o problema ocorre:
10cm x 10cm x 10cm e 0.5 kg
