### ISSUE TITLE
Não aparece na lista de seleção no frontend

### ISSUE THREAD

**Issue by claudineythomazette** [luizwbr/Correios-VirtueMart-3#4]
Estou usando Joomla 3.4.4 e VM 3.

Ele não aparece no frontend quando deve-se selecionar o método de envio, também instalei o de transportadora e esse está aparecendo normalmente.

Interessante é que depois de concluído o checkout aparece um botão CHANGE, ao lado do envio selecionado, e nele está listado o método de envio dos correios criado.

Gostaria de agradecer muito pelo trabalho e pela disponibilização gratuita do plugin.

**Comment by luizwbr** [comment]
Obrigado pelo apoio Claudiney.

Bom, faz o teste verificando este checklist de frete ( algum dos itens pode estar faltando ):
http://weber.eti.br/blog/entry/checklist-frete-virtuemart.html

**Comment by carlosjosedesign** [comment]
Olá Luiz! 
Muito obrigado por ambos os plugin: do pagseguro e o de correios.
Eu estou no mesmo problema acima, Joomla 3.5 e VirtueMart 3.0.14.
Sempre aparece "Lamentamos, nenhum método de envio corresponde às características da seu pedido."
Segui a lista:
1- Grupo de compradores ok
2- produto em cm e quilogramas
3- nenhum país no método de envio
4- plugins ativos e habilitados 
6- estou em dúvida nesse, o único caminho que achei escrito cep foi:
Loja > Informações do comprador > Informações de Faturamento. 
Não sei onde virtuemart colocou o "Endereço da loja".
O envio padrão do virtuemart funciona normalmente... Não sei mais o que configurar

Obrigado!
Grato desde já.

**Comment by luizwbr** [comment]
Esta issue está aberta em outro lugar.

**Comment by bferrazn** [comment]
Olá amigos, alguém conseguiu resolver este problema?
Fiz todas as configurações e ajuste mas o método de envio não aparece!!!!

abraço

**Comment by carlosjosedesign** [comment]
Eu ainda não consegui também, mesmo depois desta última versão...
Não sei onde está o problema.

Abraço

**Comment by bferrazn** [comment]
oi Carlos... eu resolvi... não havia criado o endereço de envio, por isso
não fazia o cálculo. ;)

abraço

_--_
_Benedito Ferraz_

(62) 98609-2503  |  (62) 3314-0301
www.bfncomunicacoes.com

2016-09-12 9:23 GMT-03:00 carlosjosedesign notifications@github.com:

**Comment by carlosjosedesign** [comment]
Isso em "Informações do comprador" ? eu preenchi aqui também...

Vlw

**Comment by bferrazn** [comment]
Fiz assim:
- Adicionei o pedido no carrinho;
- efetuei o login e fui para o checkout;
- observei que não havia endereço para envio;
- após realizar este cadastro apareceu o cálculo.

abraço

_--_
_Benedito Ferraz_

(62) 98609-2503  |  (62) 3314-0301
www.bfncomunicacoes.com

2016-09-12 9:37 GMT-03:00 carlosjosedesign notifications@github.com:

**Comment by carlosjosedesign** [comment]
Ok, vou ver com mais calma...
Muito obrigado!

**Comment by bferrazn** [comment]
Quebrei muito cabeça tb...
Mas ai fui ponto-a-ponto e deu certo ;)

boa sorte ai,
abraço

_--_
_Benedito Ferraz_

(62) 98609-2503  |  (62) 3314-0301
www.bfncomunicacoes.com

2016-09-12 10:09 GMT-03:00 carlosjosedesign notifications@github.com:
