### ISSUE TITLE
sem visualização na home

### ISSUE THREAD

**Issue by pescweb** [luizwbr/Correios-VirtueMart-3#5]
Bom dia Weber, em busca incansável pela internet por um plugin de correios, achei o seu, primeiro agradecer por distribuir no github gratuito, só que no meu site quando executo a compra ele não aparece, e ja utilizei todo os procedimentos do seu manual, gostaria de sua ajuda ou se é diferente do pago? caso possa, por favor me ajude, este é o link da loja http://lojamodelo.pescweb.com/

Obrigado pela sua atenção.
Miro Baía

**Comment by pescweb** [comment]
Ola Weber! Muitíssimo obrigado pela sua versatilidade e atenção, realmente olhando seu checklist vi que a configuração do produto estava errado (em metro).

Um abraço

Miro Baía

**Comment by luizwbr** [comment]
Por nada MIro.
