### ISSUE TITLE
Lamentamos, nenhum método de envio corresponde às características da seu pedido.

### ISSUE THREAD

**Issue by carlosjosedesign** [luizwbr/Correios-VirtueMart-3#6]
Olá Luiz! 
Muito obrigado por ambos os plugin: do pagseguro e o de correios.
Eu com um problema no plugin, uso Joomla 3.5 e VirtueMart 3.0.14.
Sempre aparece "Lamentamos, nenhum método de envio corresponde às características da seu pedido."
Segui a lista para checar:
1- Grupo de compradores ok
2- produto em cm e quilogramas
3- nenhum país no método de envio
4- plugins ativos e habilitados 
6- estou em dúvida nesse, o único caminho que achei escrito cep foi:
Loja > Informações do comprador > Informações de Faturamento. 
Não sei onde virtuemart colocou o "Endereço da loja".
O envio padrão do virtuemart funciona normalmente... Não sei mais o que configurar
Alguma idéia do que seja?

Obrigado!
Grato desde já.

**Comment by luizwbr** [comment]
Olá Carlos.
Sim, é neste lugar mesmo para configurar o cep.

Tenta cadastrar um produto com 10 x 10 x 10 cm, 0.5 kg para testar se aparecem os valores de frete.
Outra coisa que pode estar acontecendo é o usuário e senha para conectar nos serviços dos Correios com contrato. Certifique-se de que os campos estão vazios.

**Comment by carlosjosedesign** [comment]
Olá Luiz,

Estou usando essas configuração em método de pagamento:
(41106) PAC - sem contrato, também testei o  (40010) SEDEX - sem contrato
A senha, por mais que eu apague admin ******, ele volta a colocar.
É necessário cadastro nos correios?

No produto: 
em Comprimento do produto   eu deixei em Centímetros
em Peso do produto  deixei em Quilograma

Estou testando por aqui:
http://pacrugby.com.br/lojapac
se você puder dar uma olhada no backend, posso criar um usuário...

Desculpe pelo incomodo, mas é uma das poucas (ou a única) alternativa de comercio em joomla que aceite pagseguro.

Abs

**Comment by luizwbr** [comment]
Carlos, não é preciso o cadastro nos Correios para utilizar os serviços.

Atualizei recentemente o plugin, deu certo?

**Comment by carlosjosedesign** [comment]
Atualizei,
ainda não deu certo.
Uso o VirtueMart 3.0.16, e o Joomla! 3.5.1
Quando eu tiver mais tempo, posso testar em outro site, só com a loja...

**Comment by luizwbr** [comment]
Mais uma coisa Carlos, agora mesmo que não se apague o usuário e senha do método de envio, estas informações não serão enviadas para os serviços sem contrato, somente os com contrato.

Ainda assim não calcula o frete?

**Comment by carlosjosedesign** [comment]
Sim, ele não abre nem as opções de envio, nem o box de calcular o frete.

Em 28 de junho de 2016 11:21, Luiz Felipe Weber notifications@github.com
escreveu:

**Comment by luizwbr** [comment]
Carlos, atualizando a versão, este problema é resolvido.

**Comment by micaellanaro** [comment]
Boa tarde.
Estou tendo o mesmo problema. 
No meu site aqui: http://connectcellcenter.com.br/index.php/pt/
Aaparece o mesmo erro, "Lamentamos, nenhum método de envio corresponde às características da seu pedido."
versão Joomla : 3.6.5 
versão Virtuemart: 3.0.18
Aparentemente, eu fiz cada um dos passos, baixei a versão mais recente de cada plugin, e tudo continua do mesmo jeito; sem aparecer nada no front para o cliente.

**Comment by aespa** [comment]
Alguem sabe a solução? Estou com o mesmo problema!
