### ISSUE TITLE
Erro na pagina de pedido

### ISSUE THREAD

**Issue by Alexandre-df** [luizwbr/Correios-VirtueMart-3#9]
ao consultar a pagina do pedido, aparece o erro abaixo:

Notice: Undefined property: stdClass::$Handling_Fee_SN in /home/storage/0/8b/b0/facilcard/public_html/keysmarter/plugins/vmshipment/correios_virtuemartbrasil/correios_virtuemartbrasil.php on line 166

Não consigo imprimir a etiqueta de postagem, aparecem os caracteres:
%PDF-1.4 %���� 4 0 obj <>stream ����JFIF��C	   $.' ",#(7),01444'9=82<.342��C	 2!!22222222222222222222222222222222222222222222222222��/"��	���}!1AQa"q2���#B��R��$3br�

**Comment by luizwbr** [comment]
Corrigido @Alexandre-df
